# -*- coding: utf-8 -*-
"""Indeed Crawler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JG4-am1M4XL8Xjvdf4Mi3jKoKN7Zn5Lf
"""

#import relevant packages
import requests
import re
from bs4 import BeautifulSoup

url = "https://www.indeed.com/jobs?q=software%20engineer&l=San%20Francisco%2C%20CA&vjk=c95e969b6bc83fbc&advn=266360365926188"

r = requests.get(url)

html_doc = r.text

type(html_doc)

soup = BeautifulSoup(html_doc, 'html.parser')

mydivs = soup.find_all('div',id = 'mosaic-zone-jobcards')

jobcards = mydivs[0]

type(jobcards)

jobcards.find_all("a",class_ = "tapItem", partial=True)

regex = re.compile('tapItem.*')
jobs = jobcards.find_all("a",class_ = regex)

for e in jobs:
  print(e.attrs['href'])

jobs[0].attrs

